const fs = require('fs');

const lines = [];
lines.push('const { app, BrowserWindow, ipcMain, dialog } = require("electron");');
lines.push('const path = require("path");');
lines.push('const fs = require("fs");');
lines.push('');
lines.push('let mainWindow;');
lines.push('let anthropicClient = null;');
lines.push('');
lines.push('function getKeyPath() {');
lines.push('    return path.join(app.getPath("userData"), "apikey.txt");');
lines.push('}');
lines.push('');
lines.push('function loadApiKey() {');
lines.push('    try {');
lines.push('        const key = fs.readFileSync(getKeyPath(), "utf8").trim();');
lines.push('        if (key) {');
lines.push('            const Anthropic = require("@anthropic-ai/sdk");');
lines.push('            anthropicClient = new Anthropic({ apiKey: key });');
lines.push('            return true;');
lines.push('        }');
lines.push('    } catch (e) {}');
lines.push('    return false;');
lines.push('}');
lines.push('');
lines.push('function createWindow() {');
lines.push('    mainWindow = new BrowserWindow({');
lines.push('        width: 1000,');
lines.push('        height: 750,');
lines.push('        minWidth: 600,');
lines.push('        minHeight: 400,');
lines.push('        webPreferences: {');
lines.push('            preload: path.join(__dirname, "preload.js"),');
lines.push('            contextIsolation: true,');
lines.push('            nodeIntegration: false');
lines.push('        },');
lines.push('        backgroundColor: "#1e1e1e",');
lines.push('        title: "Cowork"');
lines.push('    });');
lines.push('    mainWindow.loadFile(path.join(__dirname, "renderer/index.html"));');
lines.push('}');
lines.push('');
lines.push('app.whenReady().then(() => {');
lines.push('    loadApiKey();');
lines.push('    createWindow();');
lines.push('});');
lines.push('');
lines.push('app.on("window-all-closed", () => {');
lines.push('    if (process.platform !== "darwin") { app.quit(); }');
lines.push('});');
lines.push('');
lines.push('app.on("activate", () => {');
lines.push('    if (BrowserWindow.getAllWindows().length === 0) { createWindow(); }');
lines.push('});');
lines.push('');
lines.push('ipcMain.handle("get-api-key", () => {');
lines.push('    try { return fs.readFileSync(getKeyPath(), "utf8").trim(); } catch (e) { return ""; }');
lines.push('});');
lines.push('');
lines.push('ipcMain.handle("set-api-key", (event, key) => {');
lines.push('    fs.writeFileSync(getKeyPath(), key.trim(), "utf8");');
lines.push('    const Anthropic = require("@anthropic-ai/sdk");');
lines.push('    anthropicClient = new Anthropic({ apiKey: key.trim() });');
lines.push('    return true;');
lines.push('});');
lines.push('');
lines.push('ipcMain.handle("send-message", async (event, { messages, systemPrompt, model }) => {');
lines.push('    if (!anthropicClient) {');
lines.push('        event.sender.send("stream-error", "No API key set. Please add your key in Settings.");');
lines.push('        return;');
lines.push('    }');
lines.push('    try {');
lines.push('        const stream = await anthropicClient.messages.stream({');
lines.push('            model: model || "claude-opus-4-20250514",');
lines.push('            max_tokens: 8192,');
lines.push('            system: systemPrompt,');
lines.push('            messages');
lines.push('        });');
lines.push('        for await (const chunk of stream) {');
lines.push('            if (chunk.type === "content_block_delta" && chunk.delta.type === "text_delta") {');
lines.push('                event.sender.send("stream-chunk", chunk.delta.text);');
lines.push('            }');
lines.push('        }');
lines.push('        event.sender.send("stream-done");');
lines.push('    } catch (err) {');
lines.push('        event.sender.send("stream-error", String(err));');
lines.push('    }');
lines.push('});');
lines.push('');
lines.push('ipcMain.handle("open-file", async () => {');
lines.push('    const result = await dialog.showOpenDialog(mainWindow, {');
lines.push('        properties: ["openFile"],');
lines.push('        filters: [');
lines.push('            { name: "Text Files", extensions: ["txt", "md", "js", "ts", "py", "json", "html", "css"] },');
lines.push('            { name: "All Files", extensions: ["*"] }');
lines.push('        ]');
lines.push('    });');
lines.push('    if (!result.canceled && result.filePaths.length > 0) {');
lines.push('        const filePath = result.filePaths[0];');
lines.push('        const content = fs.readFileSync(filePath, "utf-8");');
lines.push('        const fileName = path.basename(filePath);');
lines.push('        return { fileName, content };');
lines.push('    }');
lines.push('    return null;');
lines.push('});');
lines.push('');
lines.push('ipcMain.handle("save-conversations", async (event, data) => {');
lines.push('    const storePath = path.join(app.getPath("userData"), "conversations.json");');
lines.push('    fs.writeFileSync(storePath, JSON.stringify(data, null, 2));');
lines.push('});');
lines.push('');
lines.push('ipcMain.handle("load-conversations", async () => {');
lines.push('    const storePath = path.join(app.getPath("userData"), "conversations.json");');
lines.push('    if (fs.existsSync(storePath)) {');
lines.push('        return JSON.parse(fs.readFileSync(storePath, "utf-8"));');
lines.push('    }');
lines.push('    return null;');
lines.push('});');
lines.push('');
lines.push('ipcMain.handle("compact-conversation", async (event, { messages, title }) => {');
lines.push('    if (!anthropicClient) { throw new Error("No API key set."); }');
lines.push('    var NL = String.fromCharCode(10);');
lines.push('    const conversationText = messages.map(function(m) {');
lines.push('        const role = m.role === "user" ? "USER" : "CLAUDE";');
lines.push('        let content = m.content;');
lines.push('        if (Array.isArray(content)) {');
lines.push('            content = content.map(function(b) { return b.text || ""; }).join(" ");');
lines.push('        }');
lines.push('        return role + ": " + content;');
lines.push('    }).join(NL + NL);');
lines.push('    const sysPrompt = "You are a technical documentation assistant. Read the following conversation and produce a single dense structured markdown document to prime a future Claude instance with full context. Include: project overview and current state, all key decisions made and why, all code written with file paths, architecture and data flow, known issues and bugs, immediate next steps, and important developer gotchas. Be thorough but concise. Optimize for information density.";');
lines.push('    const userMsg = "Conversation title: " + title + NL + NL + conversationText;');
lines.push('    const response = await anthropicClient.messages.create({');
lines.push('        model: "claude-opus-4-20250514",');
lines.push('        max_tokens: 8192,');
lines.push('        system: sysPrompt,');
lines.push('        messages: [{ role: "user", content: userMsg }]');
lines.push('    });');
lines.push('    return response.content[0].text;');
lines.push('});');

fs.writeFileSync('src/main.js', lines.join('\n'), 'utf8');
console.log('Done! Length:', lines.join('\n').length);